name: Run_ErfanGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://sysupwsdl.vivo.com.cn/upgrade/upload/UpdateFiles/20201215073327bbcb7082271631abb20e994c8a02cb86.zip
  ROM_NAME: Generic

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: 测试 ...
         uses: actions/checkout@v2
       
       - name: 环境初始化 ...
         run: |
           sudo apt install git aria2 brotli -y
           sudo apt install p7zip-full zip unzip gawk sed curl wget openjdk-14-jdk -y
           sudo apt install unace arj python3-pip
           sudo pip3 install requests base58 pycryptodomex
       
       - name: 克隆ErfanGSI工具 ...
         run: git clone --recurse-submodules https://github.com/wenrou2554/ErfanGSIs.git
       
       - name: 开始制作GSI ...
         run: |
           sudo chmod -R 777 ErfanGSIs/*
           cd ErfanGSIs
           sudo bash url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: 压缩 ...
         run: |
           ls
           ls /home/runner/work/Github_Actions_Run_ErfanGSIs/Github_Actions_Run_ErfanGSIs/ErfanGSIs/output/
           mkdir final
           zip -r final/ErfanGSI.zip /home/runner/work/Github_Actions_Run_ErfanGSIs/Github_Actions_Run_ErfanGSIs/ErfanGSIs/output/
       
       - name: 上传至文叔叔 ...
         run: |
           echo 温柔的慈悲
           git clone https://github.com/wenrou2554/wenshushu.git
           python3 wenshushu/wss.py upload final/ErfanGSI.zip
         
            
