name: Run_ErfanGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://hugeota.d.miui.com/20.12.9/miui_LAVENDER_20.12.9_e9cdcdb88d_10.0.zip
  ROM_NAME: MIUI

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: 测试 ...
         uses: actions/checkout@v2
       
       - name: 环境初始化 ...
         run: |
           sudo apt install git aria2 brotli -y
           sudo apt install p7zip-full zip unzip gawk sed curl wget openjdk-14-jdk -y
           sudo apt install unace arj python3-pip
           sudo pip3 install requests base58 pycryptodomex
       
       - name: 克隆ErfanGSI工具 ...
         run: git clone --recurse-submodules https://github.com/wenrou2554/ErfanGSIs.git
       
       - name: 开始制作GSI ...
         run: |
           sudo chmod -R 777 ErfanGSIs/*
           cd ErfanGSIs
           sudo bash url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: 压缩 ...
         run: |
           ls /home/runner/work/Github_Actions_Run_ErfanGSIs/Github_Actions_Run_ErfanGSIs/ErfanGSIs/output/
           cd /home/runner/work/Github_Actions_Run_ErfanGSIs/Github_Actions_Run_ErfanGSIs/ErfanGSIs/
           mkdir HS
           7z a -t7z HS/ErfanGSI.7z output/* -mx=9 -mmt
           #sudo zip -r HS/ErfanGSI.zip output/*
       
       - name: 上传 ...
         run: |
           echo 温柔的慈悲
           cd /home/runner/work/Github_Actions_Run_ErfanGSIs/Github_Actions_Run_ErfanGSIs/ErfanGSIs/HS
           #curl -sL https://git.io/file-transfer | sh
           #git clone https://github.com/wenrou2554/wenshushu.git
           python3 wenshushu/wss.py upload ErfanGSI.zip
           #sudo ./transfer bit ErfanGSI.zip
         
            
